import Head from "next/head";

import { Canvas } from "@react-three/fiber";

import styles from "@/styles/Home.module.css";

import Floor from "@/components/Floor";
import Box from "@/components/Box";
import LightBulb from "@/components/LightBulb";

import { OrbitControls } from "@react-three/drei";

export default function Home() {
  return (
    <>
      <Head>
        <title>3D Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        {/* @ts-ignore */}
        <Canvas
          shadows
          className={styles.canvas}
          camera={{
            position: [-6, 7, 7],
          }}
        >
          <ambientLight color={"white"} intensity={0.5} />
          <LightBulb position={[3, 3, 0]} />
          <LightBulb position={[0, 3, 3]} />
          <LightBulb position={[-3, 3, 0]} />
          <LightBulb position={[0, 3, -3]} />
          <Box rotateX={3} rotateY={0.2} />
          <OrbitControls />
          <Floor position={[0, -1, 0]} />
        </Canvas>
      </div>
    </>
  );
}
