import React, { useState, useRef } from "react";

import Head from "next/head";

import { Canvas } from "@react-three/fiber";

import { Physics } from "@react-three/rapier";

import styles from "@/styles/Home.module.css";

import { KeyboardControls } from "@react-three/drei";

import Scene from "@/components/Scene";

export default function Home() {
  return (
    <>
      <Head>
        <title>3D Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <KeyboardControls
          map={[
            { name: "forward", keys: ["ArrowUp", "KeyW"] },
            { name: "backward", keys: ["ArrowDown", "KeyS"] },
            { name: "leftward", keys: ["ArrowLeft", "KeyA"] },
            { name: "rightward", keys: ["ArrowRight", "KeyD"] },
            { name: "jump", keys: ["Space"] },
          ]}
        >
          {/* @ts-ignore */}
          <Canvas
            shadows
            className={styles.canvas}
            camera={{
              position: [-6, 7, 7],
            }}
          >
            <Physics debug>
              <Scene />
            </Physics>
          </Canvas>
        </KeyboardControls>
      </div>
    </>
  );
}
